# Elasticsearch Configuration for BTPI-REACT
cluster.name: btpi-cluster
node.name: btpi-node-1

# Network settings
network.host: 0.0.0.0
http.port: 9200
transport.port: 9300

# Discovery settings
discovery.type: single-node
# Removed: cluster.initial_master_nodes setting is not compatible with single-node discovery

# Security settings (disabled for internal use)
xpack.security.enabled: false
xpack.security.enrollment.enabled: false
xpack.security.http.ssl.enabled: false
xpack.security.transport.ssl.enabled: false
xpack.ml.enabled: false
xpack.watcher.enabled: false
xpack.graph.enabled: false

# Memory settings
bootstrap.memory_lock: true

# Path settings
path.data: /usr/share/elasticsearch/data
path.logs: /usr/share/elasticsearch/logs

# Index settings
action.auto_create_index: true
action.destructive_requires_name: false

# Thread pool settings
thread_pool:
  write:
    size: 8
    queue_size: 200
  search:
    size: 8
    queue_size: 1000

# Index settings will be applied through templates and API calls
# (removed index level settings from node configuration)

# HTTP CORS settings
http:
  cors:
    enabled: true
    allow-origin: "*"
    allow-methods: "OPTIONS, HEAD, GET, POST, PUT, DELETE"
    allow-headers: "X-Requested-With, Content-Type, Content-Length, Authorization"

# Logging settings
logger:
  level: INFO

# Deprecation logging
deprecation:
  skip_deprecated_settings: ["*"]
