version: '3.8'

services:
  kasm-db:
    image: postgres:14-alpine
    container_name: kasm-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: kasm
      POSTGRES_USER: kasm
      POSTGRES_PASSWORD: rLKmBVMNWB0766FjPOxX1kVzWxpPvt9ec71022VPGyk=
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /home/cmndcntrl/code/btpi-react/../../data/kasm/postgres:/var/lib/postgresql/data
      - /home/cmndcntrl/code/btpi-react/config/database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - btpi-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kasm"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  kasm-redis:
    image: redis:7-alpine
    container_name: kasm-redis
    restart: unless-stopped
    command: redis-server --requirepass UWNz2J5T7/437hZK5B0gA6UJNQTa/c72BNT20CkDYVw=
    volumes:
      - /home/cmndcntrl/code/btpi-react/../../data/kasm/redis:/data
    networks:
      - btpi-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  kasm-api:
    image: kasmweb/api:1.17.0
    container_name: kasm-api
    restart: unless-stopped
    environment:
      KASM_DB_HOST: kasm-db
      KASM_DB_PORT: 5432
      KASM_DB_NAME: kasm
      KASM_DB_USER: kasm
      KASM_DB_PASSWORD: rLKmBVMNWB0766FjPOxX1kVzWxpPvt9ec71022VPGyk=
      KASM_REDIS_HOST: kasm-redis
      KASM_REDIS_PORT: 6379
      KASM_REDIS_PASSWORD: UWNz2J5T7/437hZK5B0gA6UJNQTa/c72BNT20CkDYVw=
      KASM_API_TOKEN: R5UwefrvbD5Sm4yNU0P138+KxCKS6MNFV+S1rIJwU00=
      KASM_MANAGER_TOKEN: AoF4VanLRxtI+SLYhxbS1gwLA+rlrSTaSDgGbkdsRNY=
    volumes:
      - /home/cmndcntrl/code/btpi-react/../../data/kasm/api:/opt/kasm/current/log
    depends_on:
      - kasm-db
      - kasm-redis
    networks:
      - btpi-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  kasm-manager:
    image: kasmweb/manager:1.17.0
    container_name: kasm-manager
    restart: unless-stopped
    environment:
      KASM_API_HOST: kasm-api
      KASM_API_PORT: 8080
      KASM_API_TOKEN: R5UwefrvbD5Sm4yNU0P138+KxCKS6MNFV+S1rIJwU00=
      KASM_MANAGER_TOKEN: AoF4VanLRxtI+SLYhxbS1gwLA+rlrSTaSDgGbkdsRNY=
      KASM_ADMIN_EMAIL: admin@kasm.local
      KASM_ADMIN_PASSWORD: 1rZcUruCXP6yA5w1KxJfQw==
      KASM_USER_PASSWORD: 8VqNofi9/dv5Om+nWMVufw==
    volumes:
      - /home/cmndcntrl/code/btpi-react/../../data/kasm/manager:/opt/kasm/current/log
    depends_on:
      - kasm-api
    networks:
      - btpi-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8181/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  kasm-agent:
    image: kasmweb/agent:1.17.0
    container_name: kasm-agent
    restart: unless-stopped
    privileged: true
    environment:
      KASM_API_HOST: kasm-api
      KASM_API_PORT: 8080
      KASM_API_TOKEN: R5UwefrvbD5Sm4yNU0P138+KxCKS6MNFV+S1rIJwU00=
      KASM_AGENT_HOSTNAME: kasm-agent-01
      DOCKER_HOST: unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/cmndcntrl/code/btpi-react/../../data/kasm/agent:/opt/kasm/current/log
      - /home/cmndcntrl/code/btpi-react/../../data/kasm/workspaces:/opt/kasm/current/workspaces
    depends_on:
      - kasm-api
    networks:
      - btpi-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  kasm-proxy:
    image: nginx:alpine
    container_name: kasm-proxy
    restart: unless-stopped
    ports:
      - "6443:443"
      - "6080:80"
    volumes:
      - /home/cmndcntrl/code/btpi-react/config/nginx/kasm.conf:/etc/nginx/conf.d/default.conf:ro
      - /home/cmndcntrl/code/btpi-react/config/nginx/cert.pem:/etc/nginx/ssl/cert.pem:ro
      - /home/cmndcntrl/code/btpi-react/config/nginx/key.pem:/etc/nginx/ssl/key.pem:ro
      - /home/cmndcntrl/code/btpi-react/../../data/kasm/static:/opt/kasm/current/static:ro
      - /home/cmndcntrl/code/btpi-react/../../data/kasm/downloads:/opt/kasm/current/downloads:ro
    depends_on:
      - kasm-api
      - kasm-manager
    networks:
      - btpi-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  btpi-network:
    external: true
    name: btpi-network

volumes:
  kasm-postgres:
  kasm-redis:
  kasm-api:
  kasm-manager:
  kasm-agent:
