# Elasticsearch Configuration for BTPI-REACT
cluster.name: btpi-cluster
node.name: btpi-elasticsearch
path.data: /usr/share/elasticsearch/data
path.logs: /usr/share/elasticsearch/logs

# Network settings
network.host: 0.0.0.0
http.port: 9200
transport.port: 9300

# Discovery settings (single node)
discovery.type: single-node

# Security settings (disabled for internal use)
xpack.security.enabled: false
xpack.security.transport.ssl.enabled: false
xpack.security.http.ssl.enabled: false

# Performance settings
bootstrap.memory_lock: false
indices.query.bool.max_clause_count: 8192

# Logging
logger.org.elasticsearch.deprecation: warn

# Compatibility settings
action.destructive_requires_name: false
