-- Initialize Kasm database
CREATE DATABASE IF NOT EXISTS kasm;
CREATE USER IF NOT EXISTS 'kasm'@'%' IDENTIFIED BY 'rLKmBVMNWB0766FjPOxX1kVzWxpPvt9ec71022VPGyk=';
GRANT ALL PRIVILEGES ON kasm.* TO 'kasm'@'%';
FLUSH PRIVILEGES;
