cluster.name: wazuh-cluster
node.name: wazuh-indexer-1
network.host: 0.0.0.0
http.port: 9200
discovery.type: single-node
bootstrap.memory_lock: true

# Security configuration
plugins.security.ssl.transport.enabled: false
plugins.security.ssl.http.enabled: false
plugins.security.disabled: true
plugins.security.allow_unsafe_democertificates: true
plugins.security.allow_default_init_securityindex: true
plugins.security.audit.type: noop
plugins.security.enable_snapshot_restore_privilege: true
plugins.security.check_snapshot_restore_write_privileges: true
plugins.security.system_indices.enabled: false

# Performance settings
indices.memory.index_buffer_size: 10%
thread_pool.write.queue_size: 10000
thread_pool.search.queue_size: 10000
